### ISSUE TITLE
wish: depend on `request-promise-any` instead of `request-promise-native`.

### ISSUE THREAD

**Issue by markstos** [disjunction/node-request-plus#1]
Thanks for this module. 

I've got an app that uses `request-promise` that returns Bluebird promises that I'd like to add retries to. 

This looks like a great module to use to help with that, but it appears to return native promises only. 

If it depended on [`request-promise-any`](https://www.npmjs.com/package/request-promise-any) than users could choose which promises they want returned.

**Comment by disjunction** [comment]
done in 2.0.0
